[theme]
primaryColor = "#F7A600"
backgroundColor = "#FFFFFF"
textColor = "#000000"
secondaryBackgroundColor = "#0081BE"

[server]
headless=true

[layout]
wideMode=true

[client]
showSidebarNavigation = false

